-- Data migration: remove non-rock/metal categories
-- Retains the 37 canonical rock/metal genres and their genre_cards.
-- All other genres and their cards are permanently deleted.

DELETE FROM genre_cards
WHERE genre NOT IN (
  'Black',
  'Blackened',
  'Death',
  'Death''n''Roll',
  'Deathcore',
  'Djent',
  'Doom',
  'Glam',
  'Grind',
  'Grindcore',
  'Groove',
  'Grunge',
  'Hardcore',
  'Heavy',
  'Industrial',
  'Mathcore',
  'Metal',
  'Metalcore',
  'Nu-Metal',
  'NWOBHM',
  'Post-Black',
  'Post-Doom',
  'Post-Hardcore',
  'Post-Industrial',
  'Post-Metal',
  'Post-Punk',
  'Post-Rock',
  'Power',
  'Progressive',
  'Punk',
  'Rock',
  'Screamo',
  'Shoegaze',
  'Sludge',
  'Stoner',
  'Symphonic',
  'Thrash'
);

DELETE FROM genres
WHERE name NOT IN (
  'Black',
  'Blackened',
  'Death',
  'Death''n''Roll',
  'Deathcore',
  'Djent',
  'Doom',
  'Glam',
  'Grind',
  'Grindcore',
  'Groove',
  'Grunge',
  'Hardcore',
  'Heavy',
  'Industrial',
  'Mathcore',
  'Metal',
  'Metalcore',
  'Nu-Metal',
  'NWOBHM',
  'Post-Black',
  'Post-Doom',
  'Post-Hardcore',
  'Post-Industrial',
  'Post-Metal',
  'Post-Punk',
  'Post-Rock',
  'Power',
  'Progressive',
  'Punk',
  'Rock',
  'Screamo',
  'Shoegaze',
  'Sludge',
  'Stoner',
  'Symphonic',
  'Thrash'
);
