#!/usr/bin/env bash
# Pre-deployment migration validation script
# Run this locally before shipping to catch migration issues early
#
# Usage: bash deploy/validate-migrations.sh [repo-dir]

set -euo pipefail

REPO_DIR="${1:-.}"

log_info() { echo "ℹ  $1"; }
log_warn() { echo "⚠  $1" >&2; }
log_error() { echo "❌ $1" >&2; }
log_pass() { echo "✓ $1"; }

check_migrations() {
  local migrations_dir="$REPO_DIR/prisma/migrations"
  
  if [ ! -d "$migrations_dir" ]; then
    log_warn "No migrations directory found"
    return 0
  fi
  
  local migration_count=0
  migration_count=$(find "$migrations_dir" -maxdepth 1 -type d -name "20*" 2>/dev/null | wc -l)
  
  if [ "$migration_count" -eq 0 ]; then
    log_pass "No migrations to validate"
    return 0
  fi
  
  log_info "Validating $migration_count migration(s)..."
  
  local issues=0
  
  # Check 1: Detect duplicate operations in consecutive migrations
  log_info "Check 1: Detecting duplicate index/constraint operations..."
  local prev_ops="" prev_dir="" first=true
  
  while IFS= read -r migration_dir; do
    [ -z "$migration_dir" ] && continue
    
    local migration_sql="$migration_dir/migration.sql"
    if [ ! -f "$migration_sql" ]; then
      continue
    fi
    
    # Extract CREATE INDEX, CREATE CONSTRAINT, etc. (idempotency-agnostic)
    local ops
    ops=$(sed -E 's/IF (NOT )?EXISTS//' "$migration_sql" | \
          grep -E "^(CREATE|DROP) (INDEX|CONSTRAINT|KEY|TABLE)" 2>/dev/null | \
          sed -E 's/`|"//g' | sort || true)
    
    if [ -n "$ops" ] && [ "$first" = "false" ]; then
      local ops_norm prev_ops_norm
      ops_norm=$(echo "$ops" | tr -s ' ' | md5sum | awk '{print $1}')
      prev_ops_norm=$(echo "$prev_ops" | tr -s ' ' | md5sum | awk '{print $1}')
      
      if [ "$ops_norm" = "$prev_ops_norm" ]; then
        log_error "DUPLICATE OPERATIONS in consecutive migrations:"
        log_error "  Previous: $(basename "$prev_dir")"
        log_error "  Current:  $(basename "$migration_dir")"
        log_error ""
        log_error "The current one likely auto-generated by Prisma hook."
        log_error "Delete it: rm -rf '$migration_dir'"
        issues=1
      fi
    fi
    
    [ -n "$ops" ] && prev_ops="$ops" && prev_dir="$migration_dir"
    first=false
  done < <(find "$migrations_dir" -maxdepth 1 -type d -name "20*" | sort)
  
  if [ $issues -eq 0 ]; then
    log_pass "Check 1 passed: No duplicate operations detected"
  fi
  
  # Check 2: Detect empty/comment-only migrations
  log_info "Check 2: Checking for empty migrations..."
  while IFS= read -r migration_dir; do
    [ -z "$migration_dir" ] && continue
    local migration_sql="$migration_dir/migration.sql"
    
    if [ ! -f "$migration_sql" ]; then
      log_error "Missing migration.sql: $migration_sql"
      issues=1
      continue
    fi
    
    local content_lines
    content_lines=$(grep -v '^\s*--' "$migration_sql" | grep -v '^\s*$' | wc -l)
    
    if [ "$content_lines" -lt 1 ]; then
      log_error "Empty migration: $(basename "$migration_dir")"
      log_error "Delete it: rm -rf '$migration_dir'"
      issues=1
    fi
  done < <(find "$migrations_dir" -maxdepth 1 -type d -name "20*" | sort)
  
  if [ $issues -eq 0 ]; then
    log_pass "Check 2 passed: No empty migrations"
  fi
  
  # Check 3: Verify no untracked migrations (would cause P3015)
  log_info "Check 3: Verifying all migrations are tracked in git..."
  while IFS= read -r migration_dir; do
    [ -z "$migration_dir" ] && continue
    
    if ! git ls-files --error-unmatch "$migration_dir" >/dev/null 2>&1; then
      log_error "Untracked migration directory (would cause deploy failure):"
      log_error "  $migration_dir"
      log_error "Add it: git add '$migration_dir'"
      issues=1
    fi
  done < <(find "$migrations_dir" -maxdepth 1 -type d -name "20*" | sort)
  
  if [ $issues -eq 0 ]; then
    log_pass "Check 3 passed: All migrations tracked"
  fi
  
  return $issues
}

# Main
main() {
  log_info "Pre-deployment migration validation"
  log_info "==================================="
  echo ""
  
  if ! check_migrations; then
    echo ""
    log_error "Migration validation failed!"
    log_error "Fix the issues above before deploying."
    return 1
  fi
  
  echo ""
  log_pass "All migration checks passed ✓"
  return 0
}

main "$@"
