import { EVENT_NAMES } from "@/lib/events-contract";

export const UNAVAILABLE_PLAYER_CODES = new Set([5, 100, 101, 150]);
export const PLAYER_DEBUG_ENABLED = process.env.NODE_ENV === "development" && process.env.NEXT_PUBLIC_DEBUG_PLAYER === "1";
export const FLOW_DEBUG_ENABLED = process.env.NODE_ENV === "development" && process.env.NEXT_PUBLIC_DEBUG_FLOW === "1";
export const UNAVAILABLE_OVERLAY_MESSAGE = "Sorry, this video is no longer available. Please choose another track.";
export const BROKEN_UPSTREAM_OVERLAY_MESSAGE = "This video is no longer available on YouTube and has been removed from the catalog.";
export const SEARCHING_ALTERNATIVE_OVERLAY_MESSAGE = "This video is unavailable. Searching for an alternative upload\u2026";
export const COPYRIGHT_CLAIM_OVERLAY_MESSAGE = "This video is no longer available due to a copyright claim on YouTube.";
export const REMOVED_PRIVATE_OVERLAY_MESSAGE = "This video is unavailable on YouTube because it was removed, deleted, or made private.";
export const BROKEN_UPSTREAM_AUTOADVANCE_MS = 20000;
export const BOT_BLOCK_CONFIRMATION_DELAY_MS = 5000;
export const UPSTREAM_CONNECTIVITY_OVERLAY_MESSAGE = "We could not connect to the upstream video provider for this track. This is not a YehThatRocks failure. Please try the refresh button and if that does not work, choose another track.";
export const DELETED_TRACK_OVERLAY_MESSAGE = "This track was removed from YehThatRocks.";
export const EARLY_PLAYBACK_VERIFICATION_MS = 3500;
export const STUCK_PLAYBACK_CHECK_MS = 5000;
export const STUCK_PLAYBACK_MAX_RETRIES = 3;
export const STUCK_PLAYBACK_RETRY_DELAYS_MS = [500, 1500, 3000] as const;
export const MID_PLAYBACK_BUFFERING_CHECK_MS = 1000;
export const MID_PLAYBACK_BUFFERING_THRESHOLD_MS = 8000;
export const PLAYBACK_STALL_DIRECT_IFRAME_THRESHOLD_MS = 4500;
export const PLAYBACK_STALL_PROGRESS_EPSILON_SECONDS = 0.2;
export const PLAYER_LOAD_REFRESH_HINT_DELAY_MS = 2000;
export const PLAYER_AUTO_RECONNECT_DELAY_MS = 1200;
export const MANUAL_TRANSITION_MASK_TIMEOUT_MS = 8000;
export const AUTOPLAY_KEY = "yeh-player-autoplay";
export const HISTORY_KEY = "ytr:recent-history";
export const PLAYER_VOLUME_KEY = "yeh-player-volume";
export const PLAYER_MUTED_KEY = "yeh-player-muted";
export const LAST_PLAYLIST_ID_KEY = "ytr:last-playlist-id";
export const RESUME_KEY = "yeh-player-resume";
export const HISTORY_LIMIT = 100;
export const maxEndedChoiceVideos = 12;
export const ENDED_CHOICE_BATCH_SIZE = maxEndedChoiceVideos;
export const ENDED_CHOICE_INITIAL_PREFETCH_COUNT = 24;
export const ENDED_CHOICE_SCROLL_RUNWAY_COUNT = 24;
export const ENDED_CHOICE_PREFETCH_BEFORE_END_SECONDS = 3;
export const YOUTUBE_END_SCREEN_COVER_SECONDS = 0;
export const ENDED_CHOICE_HIDE_SEEN_TOGGLE_KEY = "ytr-toggle-hide-seen-ended-choice";
export const AUTOPLAY_FALLBACK_POOL_SIZE = 12;
export const NEW_AUTOPLAY_PLAYLIST_SIZE = 96;
export const ROUTE_AUTOPLAY_QUEUE_SYNC_EVENT = EVENT_NAMES.NEW_ROUTE_QUEUE_SYNC;
